#!/bin/bash
#SBATCH -J DiT_FID
#SBATCH -A bgnp-dtai-gh
#SBATCH -p ghx4
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --gpus-per-node=1
#SBATCH --mem=128G
#SBATCH --time=08:00:00
#SBATCH -o slurm-%j.out
#SBATCH -e slurm-%j.err

set -euo pipefail


module load python/3.11.9
module load cuda/12.6.1

cd /work/nvme/betw/msalunkhe/data/imagenet

# Use all GPUs on the node
unzip  imagenet-object-localization-challenge.zip 