decoder:
  dino_hidden_size: 384
  hidden_size: 1536
  depth: 12
  num_heads: 24
  mlp_ratio: 4.0
  patch_size: 14
  output_image_size: 224
  noise_tau: 0.2

training:
  epochs: 16
  ema_decay: 0.9978
  global_batch_size: 512
  optimizer:
    lr: 2.0e-4
    betas: [0.5, 0.9]
    weight_decay: 0.0
  scheduler:
    type: cosine
    warmup_epochs: 1
    final_lr: 2.0e-5

gan:
  disc:
    arch:
      backbone_model_name: timm/vit_small_patch8_224.dino
      dino_ckpt_path: null
      freeze_backbone: true
      ks: 9
      norm_type: bn
      using_spec_norm: true
      recipe: S_8
      key_depths: [2, 5, 8, 11]
      norm_eps: 1.0e-6
    optimizer:
      lr: 2.0e-4
      betas: [0.9, 0.95]
      weight_decay: 0.0
    augment:
      prob: 1.0
      cutout: 0.0
  loss:
    disc_loss: hinge
    gen_loss: vanilla
    disc_weight: 0.75
    perceptual_weight: 1.0
    adaptive_weight: true
    disc_start: 8
    disc_upd_start: 6
    adversarial_warmup_epochs: 0.0
    lpips_start: 0
    max_d_weight: 10000.0
    disc_updates: 1
